name: elemental_isolates
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-272.0.dev <4.0.0'

# Add regular dependencies here.
dependencies: 
  elemental: ^0.0.92
  # path: ^1.8.0

dependency_overrides:
  elemental:
    path: ../elemental

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
