name: elemental_isolates
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies: 
  elemental: ^0.0.93

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
