name: nucleus_benchmark
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  benchmark_harness: ^2.2.0
  creator_core: ^0.3.2
  nucleus: any
  riverpod: ^2.0.0

dependency_overrides:
  nucleus:
    path: ../
