name: nucleus_benchmark
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  benchmark: ^0.3.0
  nucleus: any
  riverpod: ^1.0.3+1

dependency_overrides:
  nucleus:
    path: ../
