name: nucleus
description: An atomic state management utility - fast, simple and composable.
version: 0.1.29
homepage: https://github.com/tim-smart/nucleus

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
