name: nucleus
description: An atomic dependency and state management toolkit - fast, simple and composable.
version: 0.3.5
homepage: https://github.com/tim-smart/nucleus

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
