name: nucleus
description: An atomic state management utility.
version: 0.0.17+1
homepage: https://github.com/tim-smart/nucleus

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  collection: ">=1.0.0 <2.0.0"
  fast_immutable_collections: ">=7.0.0 <8.0.0"
