name: elemental
description: A toolkit for writing software in dart
version: 0.0.58
homepage: https://github.com/tim-smart/nucleus

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0

dependencies:
  fast_immutable_collections: ">=8.0.0 <9.0.0"
  fpdart: ^0.4.0
  meta: ^1.9.0
  nucleus: ^0.3.14
