name: elemental
description: A toolkit for writing software in dart. Effect-system, dependency management and more!
version: 0.0.98
homepage: https://github.com/tim-smart/elemental

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.23.1

dependencies:
  fast_immutable_collections: ">=9.0.0 <10.0.0"
  fpdart: ^0.5.0
  meta: ^1.9.0
  nucleus: ^0.3.14
