name: flutter_elemental
description: Use the package elemental with Flutter.
version: 0.0.12
homepage: https://github.com/tim-smart/nucleus

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  elemental: ^0.0.87
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_nucleus: ^0.3.5
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
