name: flutter_elemental
description: Use the package elemental with Flutter.
version: 0.0.3
homepage: https://github.com/tim-smart/nucleus

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  elemental: ^0.0.36
  flutter:
    sdk: flutter
  flutter_nucleus: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
