name: flutter_elemental
description: Use the package elemental with Flutter.
version: 0.3.1
homepage: https://github.com/tim-smart/nucleus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  elemental: ^0.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.18.0 <1.0.0"
  flutter_nucleus: ^0.4.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
