name: flutter_nucleus
description: Use the atomic state management package nucleus with Flutter.
version: 0.0.12
homepage: https://github.com/tim-smart/nucleus

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.18.0 <1.0.0"
  nucleus: ^0.0.29
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
