name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies: 
  dio: ^5.0.0
  elemental:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
